project_name: gee

builds:
  - id: gee
    main: ./main.go
    binary: gee
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
      - arm64
    ldflags: -s -w -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0

archives:
  - format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{.ProjectName}}_checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"

brews:
  - name: gee
    homepage: "https://github.com/stcrestrada/gee"
    description: "CLI tool that efficiently manages multiple Git repositories simultaneously."
    license: "MIT"
    url_template: "https://github.com/stcrestrada/gee/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    install: |
      bin.install "gee"
    test: |
      system "#{bin}/gee --version"

changelog:
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: stcrestrada
    name: gee