version: 2
before:
  hooks:
    - go mod tidy
    - go generate ./...
project_name: gee
builds:
  - id: gee
    main: ./main.go
    binary: gee
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - "6"
      - "7"
    ldflags:
      - -s -w -X main.version={{.Version}}
    ignore:
      - goos: windows
        goarch: arm64
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - name: gee
    goarm: "6"
    repository:
      owner: stcrestrada
      name: homebrew-gee
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    url_template: "https://github.com/stcrestrada/gee/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: Stephen Estrada
      email: stcrestrada@gmail.com
    homepage: "https://github.com/stcrestrada/gee"
    description: "Efficiently Manage Multiple Git Repositories."
    license: "MIT"
    skip_upload: false
