# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gee < Formula
  desc "Efficiently Manage Multiple Git Repositories."
  homepage "https://github.com/stcrestrada/gee"
  version "2.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stcrestrada/gee/releases/download/v2.1.1/gee_2.1.1_darwin_amd64.tar.gz"
      sha256 "2ab1986d5463f05899c46a4dc9d4e5f01d0f83054f781103604c84bb7864a006"

      def install
        bin.install "gee"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stcrestrada/gee/releases/download/v2.1.1/gee_2.1.1_darwin_arm64.tar.gz"
      sha256 "9baea11d17062321847abd131f0fcc0b482b94fd5fa8b2a5670e9ecd19aaf0dc"

      def install
        bin.install "gee"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/stcrestrada/gee/releases/download/v2.1.1/gee_2.1.1_linux_amd64.tar.gz"
      sha256 "089f606f4004636af850da18c0ff939968b586151e982f011bbb91e7e5a520fc"

      def install
        bin.install "gee"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stcrestrada/gee/releases/download/v2.1.1/gee_2.1.1_linux_arm64.tar.gz"
      sha256 "a1306301335f991cc9041ef50f60244377038f3fbf6b2901b55a5863e6693597"

      def install
        bin.install "gee"
      end
    end
  end
end
