[[repos]]
name = "gogo"
path = "/Users/stephenestrada/Projects/gogo"
#exclude_in_pullall = true # default is false


[[repos]]
name = "cloudsynth" # repo name
path = "/Users/stephenestrada/Projects/cloudsynth" # path to repo

[[repos]]
name = "gee" # repo name
path = "/Users/stephenestrada/Projects/gee" # path to repo

# round II
# gee install go into a directory and adds into config, directory and repo