# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gee < Formula
  desc "Manage all your git repos simultaneously."
  homepage "https://github.com/stcrestrada/gee"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/stcrestrada/gee/releases/download/v1.0.0/gee_1.0.0_darwin_arm64.tar.gz"
      sha256 "f7b63e76c9b050a923e329c7b4971ab5af887bae8e1065afc3d0dcff94c65322"

      def install
        bin.install "gee"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/stcrestrada/gee/releases/download/v1.0.0/gee_1.0.0_darwin_amd64.tar.gz"
      sha256 "f68d09ffc007b8ffdabecafb04776d046b89a3f8958f338b210f476410888319"

      def install
        bin.install "gee"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stcrestrada/gee/releases/download/v1.0.0/gee_1.0.0_linux_arm64.tar.gz"
      sha256 "deca84351567f2af74211509786faf0121270ec2f7829bf8a9237a638bbd6495"

      def install
        bin.install "gee"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/stcrestrada/gee/releases/download/v1.0.0/gee_1.0.0_linux_amd64.tar.gz"
      sha256 "1744f90156398e5ee830d7c750178464e7cd072c5486b6088b508fb93c53fb01"

      def install
        bin.install "gee"
      end
    end
  end
end
