# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gee < Formula
  desc "Efficiently Manage Multiple Git Repositories."
  homepage "https://github.com/stcrestrada/gee"
  version "2.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stcrestrada/gee/releases/download/v2.2.0/gee_2.2.0_darwin_amd64.tar.gz"
      sha256 "04235b178b45b98b643d99107118ea34669563cfb6e945f204029ed0fbc7dda1"

      def install
        bin.install "gee"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stcrestrada/gee/releases/download/v2.2.0/gee_2.2.0_darwin_arm64.tar.gz"
      sha256 "3f0b1549d784358ca92ef5f68b7919a207134976e7927bba02f69308151b55ce"

      def install
        bin.install "gee"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/stcrestrada/gee/releases/download/v2.2.0/gee_2.2.0_linux_amd64.tar.gz"
      sha256 "38b37d1c21e599ca535d46bbdae9e947b79208e654299d962a13cd347cf6c493"

      def install
        bin.install "gee"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stcrestrada/gee/releases/download/v2.2.0/gee_2.2.0_linux_arm64.tar.gz"
      sha256 "378eb4adaf8bb7ea59f2116ee205e8db57728c4583b21f66964a839f79ceb329"

      def install
        bin.install "gee"
      end
    end
  end
end
