[[repos]]
    name = "gee"
    path = "/Users/stephenestrada/test/"
    remote = "git@github.com:stcrestrada/gee.git"
[[repos]]
    branch = "main"
    name = "cloudsynth"
    path = "/Users/stephenestrada/test/"
    remote = "git@github.com:cloudsynth/cloudsynth.gi"

[[repos]]
    name = "bearly"
    path = "/Users/stephenestrada/test/"
    remote = "git@github.com:bearlyai/bearly.git"

