# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Myproject < Formula
  desc "Software to create fast and easy drum rolls."
  homepage ""
  version "0.1.2"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/stcrestrada/gee/releases/download/v0.1.2/gee_0.1.2_Darwin_x86_64.tar.gz"
    sha256 "cf60fd66bead00f4dae4ca370e3d20b2409c1256c1533a75c5527c68d919e5c3"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/stcrestrada/gee/releases/download/v0.1.2/gee_0.1.2_Darwin_arm64.tar.gz"
    sha256 "f8528609c0b5de821253a4683ca69fda84a74508dc03f0045cb256a57df562ca"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/stcrestrada/gee/releases/download/v0.1.2/gee_0.1.2_Linux_x86_64.tar.gz"
    sha256 "fda72423946edce0e385ee0e8bb111fc96021cae3722db82ff411185521c1308"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/stcrestrada/gee/releases/download/v0.1.2/gee_0.1.2_Linux_arm64.tar.gz"
    sha256 "93b59fe20563a4b5550e8f51bbc723b423487e64507000a013db6df39b59e4c0"
  end

  def install
    bin.install "gee"
  end
end
